# -*- coding: utf-8 -*-
"""Clase01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ultimatexlerion/fda4b5c6dd46bb817f0468493f67f65b/nuevo.ipynb
"""

a = 5
a

print("Hi mike")

print ('Hola "Mike" otra vez')

type(a)



a = 5
b = 6
c = a+b
print(c)
print(a+b)

if b==6:
  print(a+b)

"""Variables

puede tener un nombre corto (como: x, y, z) o un nombre descriptivo

*   No puede comenzar con un numero (ejemplo: 1sa=3)
*   Solo puede contener caracteres alfanumericos y guiones bajos (ñ_oo=4)
"""

Edad=10
edad=0
edAd=4
total=Edad+edad+edAd
print(total)

edad=10
edad=0
edad=4
total=edad+edad+edad
print(total)

"""Asignacion de variables"""

x,y,z=1,2,3
print(x,y,z)

print(x)

x = "Python es un lenguaje"
print(x)

x= "Python"
y= "es un lenguaje"
z= "de programación"
print(x,y,z)

x= "Python"
y= " es un lenguaje"
z= " de programación"
print(x+y+z)

type(x)

d=True
type(d)

x=(4,5,6)
print(type(x))

x=[3,4,5]
print(type(x))

print(x,type(x))

print(type(x))

"""Convertir"""

x=1
y=2.8
z=1j
a = float(x)
b = int(y)
c = complex(x)
print(a,b,c)

print(8==3)

print(8==8)

print(8<8)

print(9>8)

print(bool("abc"))

print(bool(15))

x="hola"
y=15
print(bool(x))
print(bool(y))















































